# Generated by Django 5.0.3 on 2024-03-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=196),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
