# Generated by Django 5.0.3 on 2024-03-12 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_bio_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
